<?php
/**
 * Created by PhpStorm.
 * User: duanpei
 * Date: 2019-07-06
 * Time: 21:55
 */

namespace DesignPatterns\Creational\Prototype;


class FooBookPrototype extends BookPrototype
{
    protected $category = 'Foo';

    public function __clone()
    {
        parent::__clone(); // TODO: Change the autogenerated stub
    }
}